* Descripción del proyecto "Web app para la gestión de la lectura"

Este proyecto está dirigido a lectores con las siguientes características:
+ Lectores entre 13 y 50 años.
+ Lectores que se sienten cómodos con la tecnología.
+ Lectores que quieren organizar y tener un mejor seguimiento de su lectura.

La problemática que buscamos resolver es una que tengo como lector, @UlisesAlexanderAM, esta consiste en que no existe una aplicación donde pueda hacer un seguimiento de lo que leo, con las funcionalidades que me gustaría y un catálogo unificador. Por ejemplo: algunas de mis lecturas las tengo guardadas en goodreads.com, pero ahí me es difícil agregar los cómics, webcómics/webtoons que sigo, tampoco están catalogados mangas, novelas ligeras y varios libros independientes.

Otra problemática es como mencione anteriormente, en sitios como goodreads.com no están catalogados libros de autores y editoriales independientes, con énfasis en los iberoamericanos. Además de esto nadie le presta atención a las revistas y revistas científicas.


Además se dividía el catálogo en las siguientes categorías: revistas, revistas científicas, novelas ligeras, mangas, cómics, webcómics/webtoons, libros de texto y libros (literatura).

Los retos tecnológicos a los que nos enfrentamos son: la falta de personal para la creación del proyecto, bajo conocimiento tecnológico de las mejores herramientas para desarrollar el producto.
