* Webapp para la gestión de la lectura. Descripción de funcionalidad.

** Funcionalidades (Requerimientos)

+ La aplicación guarda 4 estados de lectura:
  * Quiero leer
  * Leyendo
  * Leído
  * Lectura suspendida
  * Lecura abandonada.

+ Debe guardar el avance de la lectura por medio del porcentaje de lectura y/o el numero de paginas leídas del total. En el caso de los webcomics/webtoons el avance se mide por numero de tiras/capítulos leídos.

+ Debe tener la habilidad de agregar etiquetas.

+ Habilidad de buscar elementos por nombre, ISBN(opcional por el momento).

+ Habilidad de filtrar búsqueda por etiqueta, autor, editorial o sitio de alojamiento (como es el caso de algunos webcomics/webtoons), año de publicacion y categoria.

+ Los elementos deben estar agrupado en ~8 categorias: Literatura, libros de texto, novelas ligeras, mangas, comics, webcomics/webtoons, revistas y revistas científicas.

+ Calificacion de los elementos leidos con estrellas. Si el estado de lectura es Leido o lectura abandonada se habilita esta opcion, en caso contrario la opcion esta deshabilitada y oculta. La calificación promedio y un desglose de las calificaciones del elemento es visible para todos.

+ Opcionalmente el lector puede dejar una reseña y/o comentarios sobre el elemento. Las reseñas y/o comentarios pueden ser públicos o visibles para el autor. Esta opcion solo esta habilitada y visible para los elementos con un estado de lectura de leido o lectura abandonada.

+ 2 Modos de visualizacion de los elementos guardados por el usuario:
  
  * Biblioteca :: Se muestran listados todos los elementos guardados por el usuario.

  * Estanteria :: En el modo de estanteria la biblioteca, es decir, los elementos guardados por el usuario; se muestran en diferentes estantes creados por el usuario.

+ Se debe tener la posibilidad de generar reportes de lo mas leído. De manera semanal,mensual y anual. Los reportes deben ser de caracter publico.

+ Los reportes de lo mas leido son de las siguientes categorías:
  * General
  * Literatura
  * Libros de texto
  * Novelas ligeras
  * Mangas
  * Comics
  * Webcomics/Webtoons
  * Revistas
  * Revistas cientificas

+ Se debe tener la posibilidad de generar reportes individuales del catalogo. Estos reportes deben tener graficas que muestren cuantas personas han agregado ese elemento, en que estado de lectura lo tienen, los cambios del estado de lectura, semanas, meses y años entre lo mas leído; la calificacion promedio y el desglose de las calificaciones. Todo esto para uso interno, de los autores y las editoriales.

+ Se debe tener la posibilidad de general reportes editoriales del catalogo. Estos reportes tienen la misma información que los individuales pero con los elementos de una editorial determinada. Estos reportes son solo para uso interno y de las editoriales.

+ Se deben generar reportes por autor estos tienen las mismas funciones que los reportes individuales pero los elementos mostrados son los libros publicados o con participación del autor. Estos reportes son solo para uso interno y de los autores.

+ Existen 3 tipos de usuarios:
  * Lectores
  * Autores
  * Editorial
  * Administradores de la aplicación.

+ Un Autor puede ser lector pero no lo inverso.

+ La creación de elementos en las bases de datos relativas a la lectura se debe hace por medio de un formulario con los campos descritos en la siguiente sección.

** Descripción campos de los elementos de lectura.

El símbolo de * después de un campo, indica que el dicho campo es obligatorio. El campo *Link a redes sociales* esta en todas las categorias y es opcional. Todas las categorias deben tener los campos necesario para almacenar el avance de la lectura y tanto la calificacion del lector como la calificacion promedio.

+ Revistas
  * Titulo de la revista *
  * Subtitulo de la revista
  * Numero *
  * ISSN
  * Editorial*
  * Imagen de portada *
  * Numero de paginas (fisico)
  * Etiquetas
  * Link a la revista

+ Revistas cientificas
  * Titulo de la revista *
  * Subtitulo de la revista
  * Numero *
  * ISSN *
  * Editorial *
  * Imagen de portada *
  * Numero de paginas (fisico)
  * Etiquetas
  * Link a la revista

+ Novelas ligeras
  * Titulo serie *
  * Titulo japones de la serie *
  * Titulo alternativo de la serie
  * Titulo volumen
  * Titulo japones del volumen
  * Titulo alternativo del volumen
  * Numero del volumen *
  * Autor *
  * Ilustrador(es) *
  * Imagen de portada *
  * Resumen
  * Editorial *
  * Genero (etiquetas)
  * Numero de paginas (fisico)
  * ISBN
  * Link a la pagina del volumen en la pagina de la editorial
  * Links a diversas tiendas
    
+ Mangas
  * Titulo serie *
  * Titulo japones de la serie *
  * Titulo alternativo de la serie
  * Numero de tomo/volumen *
  * Autor *
  * Artista(s) *
  * Imagen de portada *
  * Resumen
  * Editorial *
  * Genero (etiquetas)
  * Numero de paginas (fisico)
  * ISBN
  * Link a la pagina del tomo en la pagina de la editorial
  * Links a diversas tiendas
  * Links a redes sociales

+ Comics
  * Titulo serie *
  * Numero del comic *
  * Autor(es) *
  * Artista(s) *
  * Imagen de la portada *
  * Resumen de la serie
  * Editorial *
  * Genero (etiquetas)
  * Link al comic en la pagina de la editorial
  * Links a diversas tiendas

+ Webcomics/webtoons
  * Titulo serie *
  * Autor *
  * Artista(s)
  * Imagen de la serie *
  * Resumen de la serie *
  * Genero (etiquetas)
  * Link al primer capitulo/tira de la serie o a una landing page de la serie.

+ Libros de texto
  * Titulo *
  * Subtitulo
  * Autor(es) *
  * Traductor(es)
  * Editorial *
  * Edicion *
  * Año *
  * País *
  * Imagen de la portada *
  * ISBN *
  * Etiquetas
  * Link a pagina del libro en el sitio de la editorial
  * Links a tiendas

+ Literatura
  * Titulo saga
  * Titulo libro *
  * Autor *
  * Ilustrador(es)
  * Traductor(es)
  * Editorial *
  * Edicion *
  * Año *
  * País *
  * ISBN
  * Link a la pagina del libro en el sitio de la editorial
  * Links a tiendas
